<img src="./images/types-of-databases.png" width="1000">

In [58]:
import pandas as pd

<img src="./images/sql-query-execution.png" width="500">

Let's create a simple example to illustrate how data might be structured in a database-like format using Pandas:

In [3]:
# Creating DataFrames to represent database tables

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['John Doe', 'Jane Smith', 'Bob Johnson', 'Alice Brown'],
    'email': ['john@example.com', 'jane@example.com', 'bob@example.com', 'alice@example.com']
})

In [4]:
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 4],
    'product': ['Widget A', 'Widget B', 'Widget C', 'Widget A', 'Widget B'],
    'quantity': [2, 1, 3, 1, 2],
    'order_date': ['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04', '2023-05-05']
})

In [5]:
print("Customers table:")
customers

Customers table:

   customer_id         name              email
0            1     John Doe   john@example.com
1            2   Jane Smith   jane@example.com
2            3  Bob Johnson    bob@example.com
3            4  Alice Brown  alice@example.com

In [6]:
print("\nOrders table:")
orders

Orders table:

   order_id  customer_id   product  quantity  order_date
0       101            1  Widget A         2  2023-05-01
1       102            2  Widget B         1  2023-05-02
2       103            1  Widget C         3  2023-05-03
3       104            3  Widget A         1  2023-05-04
4       105            4  Widget B         2  2023-05-05

In [8]:
# Displaying the primary key (customer_id) of the customers table

print("Primary Key of customers table:")
customers['customer_id']

Primary Key of customers table:

0    1
1    2
2    3
3    4
Name: customer_id, dtype: int64

In [9]:
# Showing the foreign key (customer_id) in the orders table

print("\nForeign Key in orders table:")
orders['customer_id']

Foreign Key in orders table:

0    1
1    2
2    1
3    3
4    4
Name: customer_id, dtype: int64

In [10]:
# Demonstrating the One-to-Many relationship
# Count of orders per customer

order_counts = orders['customer_id'].value_counts().sort_index()
print("\nNumber of orders per customer:")
order_counts

Number of orders per customer:

customer_id
1    2
2    1
3    1
4    1
Name: count, dtype: int64

In [11]:
# Joining tables based on the relationship

merged_data = pd.merge(customers, orders, on='customer_id')
print("\nMerged data (customers and their orders):")
merged_data

Merged data (customers and their orders):

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2023-05-01
1,1,John Doe,john@example.com,103,Widget C,3,2023-05-03
2,2,Jane Smith,jane@example.com,102,Widget B,1,2023-05-02
3,3,Bob Johnson,bob@example.com,104,Widget A,1,2023-05-04
4,4,Alice Brown,alice@example.com,105,Widget B,2,2023-05-05

SQL:
```sql
SELECT * FROM customers;
```

In [12]:
# Pandas equivalent:
# Selecting all columns from customers

customers

   customer_id         name              email
0            1     John Doe   john@example.com
1            2   Jane Smith   jane@example.com
2            3  Bob Johnson    bob@example.com
3            4  Alice Brown  alice@example.com

In [16]:
# Selecting specific columns

customers[['name', 'email']]

          name              email
0     John Doe   john@example.com
1   Jane Smith   jane@example.com
2  Bob Johnson    bob@example.com
3  Alice Brown  alice@example.com

```sql
SELECT * FROM orders WHERE quantity > 1;
```

In [17]:
# Pandas equivalent:
# Filtering orders with quantity greater than 1

orders[orders['quantity'] > 1]

   order_id  customer_id   product  quantity  order_date
0       101            1  Widget A         2  2023-05-01
2       103            1  Widget C         3  2023-05-03
4       105            4  Widget B         2  2023-05-05

```sql
SELECT * FROM orders ORDER BY quantity DESC;
```

In [18]:
# Sorting orders by quantity in descending order

orders.sort_values('quantity', ascending=False)

   order_id  customer_id   product  quantity  order_date
2       103            1  Widget C         3  2023-05-03
0       101            1  Widget A         2  2023-05-01
4       105            4  Widget B         2  2023-05-05
1       102            2  Widget B         1  2023-05-02
3       104            3  Widget A         1  2023-05-04

```sql
SELECT * FROM orders LIMIT 3;
```

In [20]:
# Pandas equivalent:
# Selecting the first 3 rows from orders

orders.head(3)

   order_id  customer_id   product  quantity  order_date
0       101            1  Widget A         2  2023-05-01
1       102            2  Widget B         1  2023-05-02
2       103            1  Widget C         3  2023-05-03

In [21]:
# SQL :
    
#     ```sql
# SELECT customer_id, product, quantity
# FROM orders
# WHERE quantity > 1
# ORDER BY quantity DESC
# LIMIT 2;
# ```

In [25]:
# Pandas equivalent:
# Combining filtering, sorting, and limiting :

orders[orders['quantity'] > 1]\
.sort_values('quantity', ascending=False)\
[['customer_id', 'product', 'quantity']]\
.head(2)

   customer_id   product  quantity
2            1  Widget C         3
0            1  Widget A         2

In [23]:
# SQL:

# ```sql
# SELECT COUNT(*) as order_count, SUM(quantity) as total_quantity
# FROM orders;
# ```

In [26]:
# Pandas equivalent:
# Calculating count of orders and sum of quantities

{
    'order_count': len(orders),
    'total_quantity': orders['quantity'].sum()
}

{'order_count': 5, 'total_quantity': np.int64(9)}

In [28]:
# SQL:

# ```sql
# SELECT customer_id, COUNT(*) as order_count
# FROM orders
# GROUP BY customer_id;
# ```

In [30]:
# Pandas equivalent:
# Grouping orders by customer and counting

orders.groupby('customer_id').size().reset_index(name='order_count')

   customer_id  order_count
0            1            2
1            2            1
2            3            1
3            4            1

In [32]:
# SQL:
    
# ```sql
# SELECT customer_id, COUNT(*) as order_count
# FROM orders
# GROUP BY customer_id
# HAVING COUNT(*) > 1;
# ```

In [34]:
# Grouping by customer, counting orders, and filtering groups with more than 1 order

orders.groupby('customer_id')\
.size()\
.reset_index(name='order_count')\
.query('order_count > 1')

   customer_id  order_count
0            1            2

<img src="./images/sql-joins.png" width="500">

In [35]:
print("Customers:")
customers

Customers:

   customer_id         name              email
0            1     John Doe   john@example.com
1            2   Jane Smith   jane@example.com
2            3  Bob Johnson    bob@example.com
3            4  Alice Brown  alice@example.com

In [36]:
print("\nOrders:")
orders

Orders:

   order_id  customer_id   product  quantity  order_date
0       101            1  Widget A         2  2023-05-01
1       102            2  Widget B         1  2023-05-02
2       103            1  Widget C         3  2023-05-03
3       104            3  Widget A         1  2023-05-04
4       105            4  Widget B         2  2023-05-05

In [37]:
# Adding a customer with no orders and an order with no matching customer

customers.loc[len(customers)] = {'customer_id': 5, 'name': 'Eva Green', 'email': 'eva@example.com'}
orders.loc[len(orders)] = {'order_id': 106, 'customer_id': 6, 'product': 'Widget D', 'quantity': 1, 'order_date': '2023-05-06'}

In [38]:
# SQL INNER JOIN:
# ```sql
# SELECT *
# FROM customers
# INNER JOIN orders ON customers.customer_id = orders.customer_id;
# ```

In [39]:
# Inner join

print("Inner Join Result:")
pd.merge(customers, orders, on='customer_id', how='inner')

Inner Join Result:

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2023-05-01
1,1,John Doe,john@example.com,103,Widget C,3,2023-05-03
2,2,Jane Smith,jane@example.com,102,Widget B,1,2023-05-02
3,3,Bob Johnson,bob@example.com,104,Widget A,1,2023-05-04
4,4,Alice Brown,alice@example.com,105,Widget B,2,2023-05-05

In [40]:
# SQL LEFT JOIN:
# ```sql
# SELECT *
# FROM customers
# LEFT JOIN orders ON customers.customer_id = orders.customer_id;
# ```

In [41]:
# Left join

print("Left Join Result:")
pd.merge(customers, orders, on='customer_id', how='left')

Left Join Result:

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101.0,Widget A,2.0,2023-05-01
1,1,John Doe,john@example.com,103.0,Widget C,3.0,2023-05-03
2,2,Jane Smith,jane@example.com,102.0,Widget B,1.0,2023-05-02
3,3,Bob Johnson,bob@example.com,104.0,Widget A,1.0,2023-05-04
4,4,Alice Brown,alice@example.com,105.0,Widget B,2.0,2023-05-05
5,5,Eva Green,eva@example.com,NaN,NaN,NaN,NaN

In [42]:
# SQL RIGHT JOIN:

# ```sql
# SELECT *
# FROM customers
# RIGHT JOIN orders ON customers.customer_id = orders.customer_id;
# ```

In [43]:
# Right join

print("Right Join Result:")
pd.merge(customers, orders, on='customer_id', how='right')

Right Join Result:

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2023-05-01
1,2,Jane Smith,jane@example.com,102,Widget B,1,2023-05-02
2,1,John Doe,john@example.com,103,Widget C,3,2023-05-03
3,3,Bob Johnson,bob@example.com,104,Widget A,1,2023-05-04
4,4,Alice Brown,alice@example.com,105,Widget B,2,2023-05-05
5,6,NaN,NaN,106,Widget D,1,2023-05-06

In [45]:
# # SQL FULL OUTER JOIN :

# ```sql
# SELECT *
# FROM customers
# FULL OUTER JOIN orders ON customers.customer_id = orders.customer_id;
# ```

In [47]:
# Full outer join

print("Full Outer Join Result:")
pd.merge(customers, orders, on='customer_id', how='outer')

Full Outer Join Result:

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101.0,Widget A,2.0,2023-05-01
1,1,John Doe,john@example.com,103.0,Widget C,3.0,2023-05-03
2,2,Jane Smith,jane@example.com,102.0,Widget B,1.0,2023-05-02
3,3,Bob Johnson,bob@example.com,104.0,Widget A,1.0,2023-05-04
4,4,Alice Brown,alice@example.com,105.0,Widget B,2.0,2023-05-05
5,5,Eva Green,eva@example.com,NaN,NaN,NaN,NaN
6,6,NaN,NaN,106.0,Widget D,1.0,2023-05-06

In [48]:
# Basic aggregations

print("Total number of orders:", len(orders))
print("Total quantity ordered:", orders['quantity'].sum())
print("Average quantity per order:", orders['quantity'].mean())
print("Maximum quantity in an order:", orders['quantity'].max())
print("Minimum quantity in an order:", orders['quantity'].min())

# Multiple aggregations at once
order_stats = orders['quantity'].agg(['count', 'sum', 'mean', 'max', 'min'])
print("\nOrder Statistics:")
order_stats

Total number of orders: 6
Total quantity ordered: 10
Average quantity per order: 1.6666666666666667
Maximum quantity in an order: 3
Minimum quantity in an order: 1

Order Statistics:

count     6.000000
sum      10.000000
mean      1.666667
max       3.000000
min       1.000000
Name: quantity, dtype: float64

In [49]:
# Group by customer_id and calculate order count and total quantity

customer_orders = orders.groupby('customer_id').agg({
    'order_id': 'count',
    'quantity': 'sum'
}).rename(columns={'order_id': 'order_count', 'quantity': 'total_quantity'})

print("Customer Order Summary:")
customer_orders

Customer Order Summary:

             order_count  total_quantity
customer_id
1                      2               5
2                      1               1
3                      1               1
4                      1               2
6                      1               1

In [50]:
# Multiple aggregations on different columns

order_analysis = orders.groupby('customer_id').agg({
    'order_id': 'count',
    'quantity': ['sum', 'mean', 'max'],
    'order_date': ['min', 'max']
})

# Flatten column names
order_analysis.columns = ['_'.join(col).strip() for col in order_analysis.columns.values]

print("Detailed Order Analysis:")
order_analysis

Detailed Order Analysis:

,order_id_count,quantity_sum,quantity_mean,quantity_max,order_date_min,order_date_max
customer_id,,,,,,
1,2,5,2.5,3,2023-05-01,2023-05-03
2,1,1,1.0,1,2023-05-02,2023-05-02
3,1,1,1.0,1,2023-05-04,2023-05-04
4,1,2,2.0,2,2023-05-05,2023-05-05
6,1,1,1.0,1,2023-05-06,2023-05-06

In [51]:
# Group by both customer_id and product

product_analysis = orders.groupby(['customer_id', 'product']).agg({
    'quantity': ['count', 'sum', 'mean']
})

print("Product Analysis by Customer:")
product_analysis

Product Analysis by Customer:

                     quantity
                        count sum mean
customer_id product
1           Widget A        1   2  2.0
            Widget C        1   3  3.0
2           Widget B        1   1  1.0
3           Widget A        1   1  1.0
4           Widget B        1   2  2.0
6           Widget D        1   1  1.0

In [52]:
# SQL HAVING
# ```sql
# SELECT customer_id, COUNT(*) as order_count
# FROM orders
# GROUP BY customer_id
# HAVING COUNT(*) > 1;
# ```

In [53]:
# Filter groups to show only customers with more than one order

frequent_customers = orders.groupby('customer_id').size().reset_index(name='order_count')
frequent_customers = frequent_customers[frequent_customers['order_count'] > 1]

print("Customers with Multiple Orders:")
frequent_customers

Customers with Multiple Orders:

   customer_id  order_count
0            1            2